version: "3"

services:
  pingfederate:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
    - SERVER_PROFILE_PATH=Customer360/pingfederate
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
      - pingnet-dmz

  pingdirectory:
    image: pingidentity/pingdirectory:latest
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
    - SERVER_PROFILE_PATH=Customer360/pingdirectory
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet-internal

  pingdatasync:
    image: pingidentity/pingdatasync:latest
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Customer360/pingdatasync
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdatasync:/opt/out
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 3636:636
      - 3443:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet-internal

  pingconfig:
    image: pricecs/pingconfigurator
    environment:
      # Collections: Solution - Customer360
      - COLLECTIONS=https://www.getpostman.com/collections/344bbc13f4ccd4ebc5f5
    volumes: 
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./postman_vars.json:/usr/src/app/postman_vars.json
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz: